version: "3.7"

services:
  mysql:
    image: mysql:5.7
    restart: always
    expose:
      - "13306"
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=nodejs
      - MYSQL_DATABASE=opentutorials
      - MYSQL_USER=nodejs
      - MYSQL_PASSWORD=nodejs
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
